### ISSUE TITLE
 Binary doesn't work

### ISSUE THREAD

**Issue by m1cl** [SanderMertens/bake#4]
Failed to execute process '/usr/local/bin/bake'. Reason:
exec: Exec format error
The file '/usr/local/bin/bake' is marked as an executable but could not be run by the operating system.

I'm using arch linux with zen-kernel

**Comment by m1cl** [comment]
I changed to bash. Seems to solve that problem. Now I got this: 

 from could not load driver 'bake.lang.c'
 from failed to load driver for language 'c'

**Comment by SanderMertens** [comment]
Thanks for trying it out! I will look into what happens if using a non-bash shell.

The second issue indicates that bake cannot find the library for the C driver. The file bake is looking for is: `~/bake/lib/libbake_lang_c.so`. If the file is there, it's an issue with the bake environment. Can you try to run the bake command you were running, and add `-v debug`?

You can also try explicitly exporting the bake environment like this:
```
export `bake env`
```
This sets the environment variables, including adding `~/bake/lib` to `LD_LIBRARY_PATH`, which should allow bake to find the library file.
